version: 0.0
os: linux
files:
  - source: demo/backend
    destination: /var/www/html
permissions:
  - object: /var/www/html
    owner: nginx
    group: nginx
hooks:
  ApplicationStop:
    - location: demo/backend/scripts/stop-server.sh
      timeout: 30
  BeforeInstall:
    - location: demo/backend/scripts/env-vars-inject.sh
      timeout: 60
    - location: demo/backend/scripts/install-dependencies.sh
      timeout: 300
  AfterInstall:
    - location: demo/backend/scripts/start-server.sh
      timeout: 30
